name: Deploy to Specific cPanel Folder

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    
    # গিটহাবের ওয়ার্নিং এড়াতে Node.js 24 এনভায়রনমেন্ট ফোর্স করা
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Get latest code
      uses: actions/checkout@v4 # v3 থেকে v4 এ আপডেট করা হয়েছে
    
    - name: Sync files to cPanel Subdomain
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./ # FTP অ্যাকাউন্টের রুট ডিরেক্টরি অনুযায়ী (যেমন: public_html/age60.myjss.edu.bd/)
